import React from 'react'

export default function MetalBlob() {
  return (
    <div>
      v
    </div>
  )
}


// /*
//   Auto-generated by Spline
// */

// import useSpline from '@splinetool/r3f-spline'
// import { OrthographicCamera } from '@react-three/drei'

// export default function MetalBlob({ ...props }) {
//   const { nodes, materials } = useSpline('https://prod.spline.design/ljkjnAnIFt7SzzLF/scene.splinecode')
//   return (
//     <>
//       <color attach="background" args={['#74757a']} />
//       <group {...props} dispose={null}>
//         <directionalLight
//           name="Directional Light"
//           castShadow
//           intensity={1}
//           shadow-mapSize-width={1024}
//           shadow-mapSize-height={1024}
//           shadow-camera-near={-10000}
//           shadow-camera-far={100000}
//           shadow-camera-left={-796.9185}
//           shadow-camera-right={796.9185}
//           shadow-camera-top={796.9185}
//           shadow-camera-bottom={-796.9185}
//           position={[-1834.38, 1130.91, 736]}
//         />
//         <mesh
//           name="Sphere"
//           geometry={nodes.Sphere.geometry}
//           material={materials['Sphere Material']}
//           castShadow
//           receiveShadow
//           position={[8.5, 2.5, 190.5]}
//         />
//         <OrthographicCamera
//           name="1"
//           makeDefault={true}
//           zoom={0.66}
//           far={100000}
//           near={-100000}
//           position={[0, 0, 1000]}
//         />
//         <hemisphereLight name="Default Ambient Light" intensity={2.39} />
//       </group>
//     </>
//   )
// }
